import Head from "next/head";
import { Inter } from "next/font/google";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { BsSun } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import { GiSwitchWeapon } from "react-icons/gi";
import Image from "next/image";
import ImageJL from "../public/image-jl.png";
import design from "../public/design1.png";
import mobile from "../public/mobile.png";
import backend from "../public/backend.png";
import web1 from "../public/1.webp";
import web2 from "../public/2.png";
import web3 from "../public/Mobile1.png";
import web4 from "../public/4.webp";
import reacticon from "../public/react.png";
import nexticon from "../public/next.js.png";
import tailwindicon from "../public/tailwindCSS.png";
import bootstrapicon from "../public/bootstrap.png";
import muiIcon from "../public/materialui.png";
import nodeicon from "../public/nodejs(2).png";
import mySQLicon from "../public/MySQL.png";
import expressicon from "../public/Express.png";
import sequelizeicon from "../public/Sequelize.png";
import githubicon from "../public/GitHub_logo.png";
import javascriptIcon from "../public/JavaScript_logo.png";
import androidicon from "../public/android.png";
import firebaseicon from "../public/Firebase.png";
import { useState } from "react";
import ParticlesBackground from "@/components/ParticlesBackground";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>John Masa Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ParticlesBackground />
      <main className="bg-white px-10 md:px-20 lg:px-40 -z-1 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="font-burtons text-xl z-10 dark:text-gray-200">
              John Masa
            </h1>
            <ul className="flex items-center z-10">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl dark:hidden"
                />
                <BsSun
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl hidden dark:block text-white"
                />
              </li>

              <li></li>
            </ul>
          </nav>
          <div className="z-10 relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-10 overflow-hidden md:h-96 md:w-96">
            <Image src={ImageJL} fill style={{ objectFit: "cover" }} />
          </div>
          <div className="text-center p-10 z-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl z-2 dark:text-teal-300">
              John Lorenz Eldon R. Masa
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl z-10 dark:text-gray-200">
              Fullstack Developer and Web Designer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 z-10 md:text-xl max-w-xl mx-auto dark:text-gray-200">
              I'm a Developer located in Laguna and I like to build amazing
              UI/UX experiences for people. join me down below and let's start
              building awesome projects together.
            </p>
          </div>
          <div className="text-xl flex justify-center text-gray-600 dark:text-gray-300">
            <a
              className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 z-10"
              href="https://www.linkedin.com/in/johnmasa/"
            >
              Contact me
            </a>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-gray-200">
              Services I offer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200">
              I offer services on Web technologies ranging from simple business
              and personal portfolio to complex web application such as admin
              panels to enterprise web applications.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-teal-500 z-10 dark:bg-white flex-1">
              <Image
                src={design}
                width={100}
                height={100}
                className="mx-auto"
              />
              <h3 className="text-lg font-medium pt-8 pb-2 text-gray-100 dark:text-gray-900">
                FRONT END TECHNOLOGIES
              </h3>
              <p className="text-md py-5 leading-8 text-gray-900">
                as someone who has a passion in creating and designing awesome
                web application, I wanted to share and help other people built
                their dream website.
              </p>
              <div className="flex justify-center gap-5 lg:flex-col"></div>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-teal-500 z-10 dark:bg-white flex-1">
              <Image
                src={backend}
                width={100}
                height={100}
                className="mx-auto"
              />
              <h3 className="text-lg font-medium pt-8 pb-2  text-gray-100 dark:text-gray-900">
                BACKEND TECHNOLOGIES
              </h3>

              <p className="text-md py-5 leading-8 text-gray-900">
                with a lot of awesome web applications we have, having a good
                backend ensures us that our data will not be accessed by anyone
                and will be kept safe.
              </p>

              <div className="flex justify-center gap-5 lg:flex-col"></div>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-teal-500 z-10 dark:bg-white flex-1">
              <Image
                src={mobile}
                width={100}
                height={100}
                className="mx-auto"
              />
              <h3 className="text-lg font-medium pt-8 pb-2  text-gray-100 dark:text-gray-900">
                MOBILE DEV TECHNOLOGIES
              </h3>
              <p className="text-md py-5 leading-8 text-gray-900">
                Creating web application / application for mobile phones for its
                convenience is also my passion and being able to speed up a
                tedious task with a mobile device can help in our day to day
                life.
              </p>
              <div className="flex justify-center gap-5 lg:flex-col"></div>
            </div>
          </div>
        </section>
        <section>
          <div className="text-5xl justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
            <h3 className="text-3xl py-1 dark:text-gray-200">TECHNOLOGIES</h3>
            <div className="flex justify-center gap-5 py-10 pb-10 rounded-xl z-10 bg-teal-500 dark:bg-gray-100">
              <Image
                src={nodeicon}
                width={50}
                height={50}
                className="mx-auto"
              />

              <Image
                src={mySQLicon}
                width={50}
                height={50}
                className="mx-auto"
              />

              <Image
                src={expressicon}
                width={50}
                height={50}
                className="mx-auto"
              />

              <Image
                src={sequelizeicon}
                width={50}
                height={50}
                className="mx-auto"
              />

              <Image
                src={githubicon}
                width={50}
                height={50}
                className="mx-auto"
              />

              <Image
                src={javascriptIcon}
                width={50}
                height={50}
                className="mx-auto"
              />
              <Image
                src={reacticon}
                width={50}
                height={50}
                className="mx-auto"
              />

              <Image
                src={nexticon}
                width={50}
                height={50}
                className="mx-auto"
              />

              <Image
                src={tailwindicon}
                width={50}
                height={50}
                className="mx-auto"
              />

              <Image src={muiIcon} width={50} height={50} className="mx-auto" />

              <Image
                src={bootstrapicon}
                width={50}
                height={50}
                className="mx-auto"
              />
              <Image
                src={androidicon}
                width={50}
                height={50}
                className="mx-auto"
              />

              <Image
                src={firebaseicon}
                width={50}
                height={50}
                className="mx-auto"
              />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-gray-200">Portfolio</h3>
          </div>

          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 z-10">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
              />
            </div>
            <div className="basis-1/3 flex-1 z-10">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
              />
            </div>
            <div className="basis-1/3 flex-1 z-10">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
              />
            </div>
            <div className="basis-1/3 flex-1 z-10">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
              />
            </div>
          </div>
        </section>
        <footer>
          <span class="block text-sm text-gray-500 sm:text-center dark:text-gray-400">
            © 2024{" "}
            <a
              href="https://www.linkedin.com/in/johnmasa/"
              class="hover:underline"
            >
              John Lorenz Eldon R Masa
            </a>
            . All Rights Reserved.
          </span>
        </footer>
      </main>
    </div>
  );
}
